CREATE TABLE IF NOT EXISTS users (
  id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  username VARCHAR(255) NOT NULL,
  age INTEGER NOT NULL,
  gender VARCHAR(255) NOT NULL,
  nationality VARCHAR(255) NOT NULL,
  balance INTEGER NOT NULL,
);